name = input("Please enter your name: ")
print ("Hello",name,"!")
lecture_day = (input("What are your lecture days? "))
lecture_time = (input("Which time do you have the lectures on those days? "))
lab_day = (input("What are your lab session days? "))
lab_time = (input("Which time do you have the lab session on those days? "))
print ("Welcome to CSC 1301 Principles of Computer Science Course!")
print ("Our class is held every",lecture_day,"at",lecture_time,".")
print ("Our lab session is held every",lab_day,"at",lab_time,".")
