wage = int(input("Please enter your hourly wage: "))
hours = int(input("Please enter the number of hours worked per week: "))
weeks = int(input("Please enter the number of weeks worked this year: "))
annual_salary = str(wage*hours*weeks)
print ("Your salary so far this year is $" + annual_salary)
